singleQuote: true
semi: false
printWidth: 100
trailingComma: none
endOfLine: 'lf'
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-organize-imports'
importOrderSeparation: true
importOrderSortSpecifiers: true
